### ISSUE TITLE
Please update project headline

### ISSUE THREAD

**Issue by mfld-fr** [rickhousley/happn#12]
I would now replace _"Python module for interacting with the Happn's REST API"_ by _"Python / PHP modules for interacting with the Happn's REST API"_ to avoid confusion in visitors mind (because GitHub tags projects with their predominant language).

**Comment by rickhousley** [comment]
Headline has been fixed. The main Readme still needS to be changed and there needs to be a PHP and python one in each modules subfolder explaining how to set them up.

**Comment by mfld-fr** [comment]
It seems that my request was not clear enough : I did not request to change the README (I can update it myself as other sources), but the headline that is just below the navigation bar in the "< > Code" tab, and that appears in the results when searching "happn" in GitHub. Could you please update that one, please ?

**Comment by rickhousley** [comment]
My bad. Updated.

**Comment by mfld-fr** [comment]
Sorry to come back on this issue, but it looks like the project headline is still the same:
`Python module for interacting with the Happn's REST API`

Could you please update it to:
`Python & PHP modules for interacting with the Happn's REST API`

**Comment by rickhousley** [comment]
Corrected. Please close the issue if the update is satisfactory.

**Comment by mfld-fr** [comment]
Headline now corrected.
Thank you very much Rick !
